### ISSUE TITLE
google drive client error - Cannot mask with non-boolean array containing NA\NaN values

### ISSUE THREAD

**Issue by InventoRyAlpaca** [czbiohub-sf/MS-AutoQC#86]
Seems to happen each time the client pulls info from drive, after the source updates with newly processed files.

Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "c:\users\ira.gray\ms-autoqc-venv\py38_autoqc\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\ira.gray\ms-autoqc-venv\py38_autoqc\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\ira.gray\ms-autoqc-venv\py38_autoqc\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\ira.gray\ms-autoqc-venv\py38_autoqc\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "c:\users\ira.gray\ms-autoqc-venv\py38_autoqc\lib\site-packages\dash\dash.py", line 1259, in dispatch
    ctx.run(
  File "c:\users\ira.gray\ms-autoqc-venv\py38_autoqc\lib\site-packages\dash\_callback.py", line 439, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "c:\users\ira.gray\ms-autoqc-venv\py38_autoqc\lib\site-packages\ms_autoqc\DashWebApp.py", line 2616, in apply_sample_filter_to_plots
    df_samples = df_samples.loc[df_samples["Polarity"].str.contains(polarity)]
  File "c:\users\ira.gray\ms-autoqc-venv\py38_autoqc\lib\site-packages\pandas\core\indexing.py", line 967, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "c:\users\ira.gray\ms-autoqc-venv\py38_autoqc\lib\site-packages\pandas\core\indexing.py", line 1181, in _getitem_axis
    elif com.is_bool_indexer(key):
  File "c:\users\ira.gray\ms-autoqc-venv\py38_autoqc\lib\site-packages\pandas\core\common.py", line 144, in is_bool_indexer
    raise ValueError(na_msg)
ValueError: Cannot mask with non-boolean array containing NA / NaN values

**Comment by InventoRyAlpaca** [comment]
Saw this with pandas 2.1.3 as well on python 3.12, I believe. But can't find the log now to confirm 100%.
